name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    # Store release build 
    - uses: actions/upload-artifact@v4
      with:
        name: Capture release build of pub-sub-tiny
        path: target/release/pub-sub-tiny # or path/to/artifact